a=float(input("Ingrese el valor de a: "))
b=float(input("Ingrese el valor de b: "))
c=float(input("Ingrese el valor de c: "))
ecuacion= ((c+5)*(b**2-3*a*c)*a**2)/(4*a)
print (f"La respuesta es: {ecuacion}")